Hc review assistant
holidaycheck/tech-blog pull request #190
Opened 2023-04-18 13:17 UTC by konarkmodi

Fixes #??.

Changes proposed in the PR fix/change the following:
- 
- 
- 

To the reviewer: *If you approve this PR, please merge it right away too.*
(Why merging it right away? It makes the PR valuable as soon as it is approved.
The author wrote it with the intention for it to go live, so let's do them the favor as soon as possible :).
Thanks.)

2023-04-18 14:47 UTC, tmayer reviewed
I was wondering whether we want to add a paragraph about the underlying technology that was used to create the assistant? I wouldn't give away too much in here, but just mentioning some things might whet the reader's appetite.

2023-04-18 20:18 UTC, TejashreeAher requested changes

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +***Generative AI can help people find the right way to express themselves***
Calling people for reviews can be the next section with more highlight on the raffle :)

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +We strive to reduce the barrier to entry for users wanting to write a review. One does not need to be an expert in any language to submit a review, nor does one have to spend hours finding the words
barrier-to-entry is one word

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +We strive to reduce the barrier to entry for users wanting to write a review. One does not need to be an expert in any language to submit a review, nor does one have to spend hours finding the words
"We strive to reduce the barrier-to-entry in writing a review" can be a shorter sentence

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +We strive to reduce the barrier to entry for users wanting to write a review. One does not need to be an expert in any language to submit a review, nor does one have to spend hours finding the words
One does not need to be a language expert to submit a review, nor does one have to spend hours finding the right words to use

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +We strive to reduce the barrier to entry for users wanting to write a review. One does not need to be an expert in any language to submit a review, nor does one have to spend hours finding the words
"The assistant comes handy. Just start speaking or typing and the assistant helps to write a proper narrative with just a few words." (to make it more attractive !)

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +In the beta phase we are only collecting two types of content: Text and audio. If you wish to submit pictures, they can still be uploaded via our regular system: https://www.holidaycheck.de/wcf
"text" also in small.

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +This is a fair question and one we ought to ask ourselves. However, reviews written by this assistant will still go through all our strict checks and balances. We would not start by publishing them d
This is a fair question we ought to ask ourselves. However ...

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +This is a fair question and one we ought to ask ourselves. However, reviews written by this assistant will still go through all our strict checks and balances. We would not start by publishing them d
This is slightly complicated to ask. Do we mean,
"This is a fair question we ought to ask ourselves. Users, even today, can use assistants outside of HolidayCheck to write reviews and we should definitely embrace the technology trend. However, all reviews submitted to HC, including ones generated by this assistant go through all our strict checks and balances, thus not diluting the brand value and authenticity."

2023-04-18 20:18 UTC, TejashreeAher commented on _posts/2023-04-18-ai-based-assistant.md
> +Yes, these reviews are labeled and, by the way, go through the same rigorous quality controls and review processes before they are published. Currently the submitted reviews will not go online.
"the reviews generated by this tool, whenever published online, will be labeled after going through the same rigorous quality controls and review processes. Currently, the reviews do not go online in the Beta phase." 
would make it more clear ?

2023-07-03 19:08 UTC, TejashreeAher approved these changes

2023-07-03 19:12 UTC, merged